#!/usr/bin/env node
/**
 * PGP Setup Entry Point - INST-029
 * Epic 5, Story 5 - Create npm run pgp:setup command entry point
 *
 * Main entry point for PGP key management.
 * Usage: npm run pgp:setup
 * Flags:
 *   --generate  Skip to key generation
 *   --sign      Skip to config signing
 *   --status    Show key status only
 *   --help      Show help message
 *
 * @module pgp-setup/index
 * @author BlackUnicorn.Tech
 * @version 1.0.0
 */

import { fileURLToPath } from 'url';
import path from 'path';
import fs from 'fs';
import chalk from 'chalk';
import { select, confirm } from '../../cli/prompts.js';

// Import pgp-setup components
import { checkGpgCapability, getInstallInstructions } from './gpg-checker.js';
import { runKeyGeneration, checkExistingKey } from './key-generator.js';
import { exportKeys, getKeysDirectory } from './key-export.js';
import { signAllConfigs, getSignedFiles, SIGNABLE_CONFIGS } from './config-signer.js';

// ESM equivalent of __dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ============================================================================
// Constants
// ============================================================================

export const VERSION = '1.0.0';
export const PGP_CONFIG_FILENAME = 'pgp-config.yaml';
export const PGP_CONFIG_PATH = '_bmad/_config/pgp-config.yaml';

export const HELP_TEXT = `
BMAD PGP Setup Wizard v${VERSION}

Usage:
  npm run pgp:setup              Interactive PGP key management
  npm run pgp:setup -- --generate  Generate new PGP key
  npm run pgp:setup -- --sign      Re-sign configuration files
  npm run pgp:setup -- --status    Show current key status
  npm run pgp:setup -- --help      Show this help message

Actions:
  - Check GPG availability on your system
  - Generate new PGP keys for signing
  - Export public keys for sharing
  - Sign configuration files

Examples:
  npm run pgp:setup                    # Interactive mode
  npm run pgp:setup -- --status        # Check current PGP key
  npm run pgp:setup -- --generate      # Generate new key directly
  npm run pgp:setup -- --sign          # Re-sign all config files
`;

// ============================================================================
// Banner Display
// ============================================================================

/**
 * Display banner for the PGP setup wizard
 */
function displayBanner() {
  console.log(chalk.bold.cyan('\n' + '='.repeat(64)));
  console.log(chalk.bold.cyan('                 BMAD PGP Setup Wizard'));
  console.log(chalk.bold.cyan('                   Version ' + VERSION));
  console.log(chalk.bold.cyan('='.repeat(64) + '\n'));
}

// ============================================================================
// PGP Configuration File Handling
// ============================================================================

/**
 * Read the PGP configuration file
 * @param {string} projectRoot - Project root directory
 * @returns {object|null} Parsed config or null if not found
 */
export function readPgpConfig(projectRoot = process.cwd()) {
  const configPath = path.join(projectRoot, PGP_CONFIG_PATH);

  if (!fs.existsSync(configPath)) {
    return null;
  }

  try {
    const content = fs.readFileSync(configPath, 'utf8');
    // Simple YAML parsing for our config format
    const config = {};
    const lines = content.split('\n');

    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith('#')) {
        const colonIndex = trimmed.indexOf(':');
        if (colonIndex > 0) {
          const key = trimmed.slice(0, colonIndex).trim();
          let value = trimmed.slice(colonIndex + 1).trim();
          // Remove quotes if present
          if ((value.startsWith("'") && value.endsWith("'")) ||
              (value.startsWith('"') && value.endsWith('"'))) {
            value = value.slice(1, -1);
          }
          config[key] = value;
        }
      }
    }

    return config;
  } catch (error) {
    return null;
  }
}

/**
 * Write the PGP configuration file
 * @param {object} config - Configuration to write
 * @param {string} projectRoot - Project root directory
 * @returns {{success: boolean, path: string, error: string|null}}
 */
export function writePgpConfig(config, projectRoot = process.cwd()) {
  const configPath = path.join(projectRoot, PGP_CONFIG_PATH);
  const configDir = path.dirname(configPath);

  try {
    // Ensure directory exists
    if (!fs.existsSync(configDir)) {
      fs.mkdirSync(configDir, { recursive: true });
    }

    // Generate YAML content
    const lines = [
      '# BMAD PGP Configuration',
      '# Generated by PGP Setup Wizard v' + VERSION,
      '# Last updated: ' + new Date().toISOString(),
      ''
    ];

    for (const [key, value] of Object.entries(config)) {
      if (Array.isArray(value)) {
        lines.push(key + ':');
        for (const item of value) {
          lines.push('  - ' + item);
        }
      } else {
        lines.push(key + ': ' + (typeof value === 'string' ? "'" + value + "'" : value));
      }
    }

    fs.writeFileSync(configPath, lines.join('\n') + '\n', 'utf8');

    return { success: true, path: configPath, error: null };
  } catch (error) {
    return { success: false, path: configPath, error: error.message };
  }
}

// ============================================================================
// Status Display
// ============================================================================

/**
 * Show current PGP key status
 * @param {string} projectRoot - Project root directory
 * @returns {object} Status information
 */
export function showCurrentKeyStatus(projectRoot = process.cwd()) {
  console.log(chalk.bold('\nPGP Key Status:\n'));

  const config = readPgpConfig(projectRoot);

  if (!config || !config.fingerprint) {
    console.log(chalk.yellow('  No PGP key configured.'));
    console.log(chalk.dim('  Run pgp:setup to generate a new key.\n'));
    return { hasKey: false, config: null };
  }

  // Display key information
  console.log(chalk.green('  Key configured:'));
  console.log('    Fingerprint: ' + chalk.cyan(config.fingerprint || 'N/A'));

  if (config.key_id) {
    console.log('    Key ID:      ' + chalk.cyan(config.key_id));
  }
  if (config.user_name) {
    console.log('    User:        ' + chalk.cyan(config.user_name));
  }
  if (config.email) {
    console.log('    Email:       ' + chalk.cyan(config.email));
  }
  if (config.created_at) {
    console.log('    Created:     ' + chalk.dim(config.created_at));
  }

  console.log();
  return { hasKey: true, config };
}

/**
 * Show signed files status
 * @param {string} projectRoot - Project root directory
 */
export async function showSignedFilesStatus(projectRoot = process.cwd()) {
  console.log(chalk.bold('Signed Files:\n'));

  const signedFiles = await getSignedFiles(projectRoot);

  if (signedFiles.length === 0) {
    console.log(chalk.yellow('  No signed configuration files found.'));
    console.log(chalk.dim('  Use --sign to sign configuration files.\n'));
    return;
  }

  console.log(chalk.green('  ' + signedFiles.length + ' file(s) signed:\n'));
  for (const filePath of signedFiles) {
    const relativePath = path.relative(projectRoot, filePath);
    console.log('    ' + chalk.cyan('*') + ' ' + relativePath);
  }
  console.log();
}

// ============================================================================
// User Prompts
// ============================================================================

/**
 * Prompt user for action when key exists
 * @returns {Promise<string>} Selected action
 */
export async function promptForAction() {
  const choices = [
    { name: 'View key information', value: 'view' },
    { name: 'Re-sign configuration files', value: 'sign' },
    { name: 'Generate new key (replace existing)', value: 'generate' },
    { name: 'Exit', value: 'exit' }
  ];

  const action = await select({
    message: 'What would you like to do?',
    choices
  });

  return action;
}

/**
 * Prompt user to confirm key generation
 * @returns {Promise<boolean>} User confirmation
 */
export async function confirmKeyGeneration() {
  const result = await confirm({
    message: 'Would you like to generate a new PGP key?',
    initialValue: true
  });

  return result;
}

/**
 * Prompt user to confirm replacing existing key
 * @returns {Promise<boolean>} User confirmation
 */
export async function confirmReplaceKey() {
  const result = await confirm({
    message: chalk.yellow('A key already exists. Generate a new one? This will replace the existing key.'),
    initialValue: false
  });

  return result;
}

// ============================================================================
// Main Orchestration
// ============================================================================

/**
 * Run the PGP setup wizard
 * @param {Object} options - Setup options
 * @param {string} [options.projectRoot] - Project root directory
 * @param {boolean} [options.generate] - Skip to key generation
 * @param {boolean} [options.sign] - Skip to config signing
 * @param {boolean} [options.status] - Show status only
 * @param {boolean} [options.silent] - Suppress banner output
 * @returns {Promise<{success: boolean, action: string, result: object|null, error: string|null}>}
 */
export async function runPgpSetup(options = {}) {
  const {
    projectRoot = process.cwd(),
    generate = false,
    sign = false,
    status = false,
    silent = false
  } = options;

  // Display banner unless silent mode
  if (!silent) {
    displayBanner();
  }

  // Step 1: Check GPG capability
  console.log(chalk.dim('Checking GPG availability...\n'));
  const gpgStatus = await checkGpgCapability();

  if (!gpgStatus.available) {
    console.log(chalk.red('GPG is not available on this system.\n'));
    console.log(chalk.yellow('Installation Instructions:'));
    console.log(getInstallInstructions());
    console.log();
    return {
      success: false,
      action: 'check',
      result: gpgStatus,
      error: 'GPG not available'
    };
  }

  console.log(chalk.green(`GPG found: v${gpgStatus.version} at ${gpgStatus.path}\n`));

  // Step 2: Check current key status
  const keyStatus = showCurrentKeyStatus(projectRoot);

  // Handle status-only mode
  if (status) {
    if (keyStatus.hasKey) {
      await showSignedFilesStatus(projectRoot);
    }
    return {
      success: true,
      action: 'status',
      result: keyStatus,
      error: null
    };
  }

  // Handle direct sign mode
  if (sign) {
    if (!keyStatus.hasKey) {
      console.log(chalk.red('No PGP key found. Generate a key first.\n'));
      return {
        success: false,
        action: 'sign',
        result: null,
        error: 'No key available for signing'
      };
    }

    console.log(chalk.dim('\nSigning configuration files...\n'));
    const signResult = await signAllConfigs({
      fingerprint: keyStatus.config.fingerprint,
      projectRoot
    });

    if (signResult.success) {
      console.log(chalk.green(`Signed ${signResult.signedFiles.length} file(s) successfully.\n`));
      for (const filePath of signResult.signedFiles) {
        const relativePath = path.relative(projectRoot, filePath);
        console.log(`  ${chalk.cyan('*')} ${relativePath}`);
      }
      console.log();
    } else {
      console.log(chalk.red(`Failed to sign files: ${signResult.error}\n`));
    }

    return {
      success: signResult.success,
      action: 'sign',
      result: signResult,
      error: signResult.error
    };
  }

  // Handle direct generate mode
  if (generate) {
    if (keyStatus.hasKey) {
      const shouldReplace = await confirmReplaceKey();
      if (!shouldReplace) {
        console.log(chalk.yellow('\nKey generation cancelled.\n'));
        return {
          success: true,
          action: 'cancelled',
          result: null,
          error: null
        };
      }
    }

    return await performKeyGeneration(projectRoot);
  }

  // Interactive mode
  if (keyStatus.hasKey) {
    const action = await promptForAction();

    switch (action) {
      case 'view':
        await showSignedFilesStatus(projectRoot);
        return { success: true, action: 'view', result: keyStatus, error: null };

      case 'sign':
        console.log(chalk.dim('\nSigning configuration files...\n'));
        const signResult = await signAllConfigs({
          fingerprint: keyStatus.config.fingerprint,
          projectRoot
        });

        if (signResult.success) {
          console.log(chalk.green(`Signed ${signResult.signedFiles.length} file(s) successfully.\n`));
        }

        return {
          success: signResult.success,
          action: 'sign',
          result: signResult,
          error: signResult.error
        };

      case 'generate':
        const shouldReplace = await confirmReplaceKey();
        if (!shouldReplace) {
          console.log(chalk.yellow('\nKey generation cancelled.\n'));
          return { success: true, action: 'cancelled', result: null, error: null };
        }
        return await performKeyGeneration(projectRoot);

      case 'exit':
      default:
        console.log(chalk.dim('\nExiting PGP setup.\n'));
        return { success: true, action: 'exit', result: null, error: null };
    }
  } else {
    // No key exists, offer to generate
    const shouldGenerate = await confirmKeyGeneration();
    if (!shouldGenerate) {
      console.log(chalk.yellow('\nKey generation skipped.\n'));
      return { success: true, action: 'skipped', result: null, error: null };
    }

    return await performKeyGeneration(projectRoot);
  }
}

/**
 * Perform key generation and export
 * @param {string} projectRoot - Project root directory
 * @returns {Promise<object>} Generation result
 */
async function performKeyGeneration(projectRoot) {
  console.log(chalk.dim('\nStarting key generation...\n'));

  // Generate the key
  const genResult = await runKeyGeneration({ projectRoot });

  if (!genResult.success) {
    console.log(chalk.red(`Key generation failed: ${genResult.error}\n`));
    return {
      success: false,
      action: 'generate',
      result: genResult,
      error: genResult.error
    };
  }

  console.log(chalk.green('Key generated successfully!\n'));
  console.log(`  Fingerprint: ${chalk.cyan(genResult.fingerprint)}`);
  console.log(`  Key ID:      ${chalk.cyan(genResult.keyId)}`);
  console.log(`  Name:        ${genResult.name}`);
  console.log(`  Email:       ${genResult.email}\n`);

  // Export keys
  console.log(chalk.dim('Exporting public key...\n'));
  const exportResult = await exportKeys(genResult.fingerprint, projectRoot, { silent: true });

  if (exportResult.success) {
    console.log(chalk.green(`Public key exported to: ${exportResult.publicKeyPath}\n`));
  }

  // Save configuration
  const configResult = writePgpConfig({
    fingerprint: genResult.fingerprint,
    key_id: genResult.keyId,
    user_name: genResult.name,
    email: genResult.email,
    created_at: genResult.createdAt,
    public_key_path: exportResult.publicKeyPath
  }, projectRoot);

  if (configResult.success) {
    console.log(chalk.green(`Configuration saved to: ${configResult.path}\n`));
  }

  // Offer to sign configs
  const signNow = await confirm({
    message: 'Would you like to sign configuration files now?',
    initialValue: true
  });

  if (signNow) {
    console.log(chalk.dim('\nSigning configuration files...\n'));
    const signResult = await signAllConfigs({
      fingerprint: genResult.fingerprint,
      projectRoot
    });

    if (signResult.success) {
      console.log(chalk.green(`Signed ${signResult.signedFiles.length} file(s) successfully.\n`));
    }
  }

  console.log(chalk.bold.green('\nPGP setup complete!\n'));

  return {
    success: true,
    action: 'generate',
    result: {
      generation: genResult,
      export: exportResult,
      config: configResult
    },
    error: null
  };
}

// ============================================================================
// CLI Argument Parsing
// ============================================================================

/**
 * Parse command line arguments
 * @returns {Object} Parsed options
 */
export function parseArgs() {
  const args = process.argv.slice(2);
  const options = {
    generate: false,
    sign: false,
    status: false,
    help: false
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];

    if (arg === '--generate' || arg === '-g') {
      options.generate = true;
    } else if (arg === '--sign' || arg === '-s') {
      options.sign = true;
    } else if (arg === '--status') {
      options.status = true;
    } else if (arg === '--help' || arg === '-h') {
      options.help = true;
    }
  }

  return options;
}

/**
 * Display help message
 */
function showHelp() {
  console.log(HELP_TEXT);
}

// ============================================================================
// ESM Entry Point Detection
// ============================================================================

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const options = parseArgs();

  if (options.help) {
    showHelp();
    process.exit(0);
  }

  runPgpSetup(options)
    .then(result => {
      if (result.success) {
        process.exit(0);
      } else {
        process.exit(1);
      }
    })
    .catch(error => {
      console.error(chalk.red('\nPGP setup failed:'));
      console.error(chalk.red(`  ${error.message}\n`));
      if (process.env.DEBUG) {
        console.error(error.stack);
      }
      process.exit(1);
    });
}

// ============================================================================
// Exports for Programmatic Use
// ============================================================================

export default {
  runPgpSetup,
  showCurrentKeyStatus,
  showSignedFilesStatus,
  readPgpConfig,
  writePgpConfig,
  promptForAction,
  confirmKeyGeneration,
  confirmReplaceKey,
  parseArgs,
  VERSION,
  HELP_TEXT,
  PGP_CONFIG_PATH
};
