#!/bin/bash
# BMAD Security Remediation Script
# Generated by Bastion (Security Architect) - Story 4.1
# Implements critical security fixes and hardening measures

set -euo pipefail

echo "🔐 BMAD Security Remediation Suite"
echo "═══════════════════════════════════"
echo "⚠️  This script will implement critical security fixes"
echo "📋 Review the SECURITY-SANITIZATION-REPORT.md before proceeding"
echo ""

# Configuration
BACKUP_DIR="_bmad-security-backup-$(date +%Y%m%d-%H%M%S)"
REPO_ROOT="$(pwd)"
LOG_FILE="security-remediation.log"

# Initialize logging
exec 1> >(tee -a "$LOG_FILE")
exec 2> >(tee -a "$LOG_FILE" >&2)

echo "🗓️ Started: $(date)"
echo "📁 Repository: $REPO_ROOT"
echo "💾 Backup Directory: $BACKUP_DIR"
echo "📝 Log File: $LOG_FILE"
echo ""

# Create backup directory
mkdir -p "$BACKUP_DIR"

# Function to backup sensitive files before modification
backup_file() {
    local file="$1"
    if [[ -f "$file" ]]; then
        local backup_path="$BACKUP_DIR/$(basename "$file")"
        cp "$file" "$backup_path"
        echo "📦 Backed up: $file → $backup_path"
    fi
}

# Function to secure file permissions
secure_permissions() {
    local file="$1"
    local perms="$2"
    if [[ -f "$file" ]]; then
        chmod "$perms" "$file"
        echo "🔒 Secured permissions: $file ($perms)"
    fi
}

echo "1️⃣ SECURING SENSITIVE FILES"
echo "──────────────────────────────────"

# Secure .bmad-key if present
if [[ -f ".bmad-key" ]]; then
    backup_file ".bmad-key"
    secure_permissions ".bmad-key" "600"
    echo "🔑 .bmad-key secured (read/write owner only)"
else
    echo "✅ .bmad-key not present in working directory"
fi

# Secure .bmad-token if present
if [[ -f ".bmad-token" ]]; then
    backup_file ".bmad-token"
    secure_permissions ".bmad-token" "600"
    echo "🎫 .bmad-token secured (read/write owner only)"
else
    echo "✅ .bmad-token not present in working directory"
fi

echo ""

echo "2️⃣ VALIDATING GITIGNORE CONFIGURATION"
echo "──────────────────────────────────────────"

# Verify critical patterns in .gitignore
REQUIRED_PATTERNS=(".bmad-key" ".bmad-token" ".env" ".env.local" "*.env" "node_modules/" ".DS_Store")

if [[ -f ".gitignore" ]]; then
    backup_file ".gitignore"

    for pattern in "${REQUIRED_PATTERNS[@]}"; do
        if grep -q "^$pattern$" .gitignore; then
            echo "✅ .gitignore contains: $pattern"
        else
            echo "⚠️  Missing pattern in .gitignore: $pattern"
        fi
    done
else
    echo "❌ .gitignore file not found"
    exit 1
fi

echo ""

echo "3️⃣ CHECKING GIT REPOSITORY STATUS"
echo "─────────────────────────────────────"

# Verify sensitive files are not tracked
if git ls-files | grep -E "\\.(bmad-key|bmad-token)$"; then
    echo "❌ CRITICAL: Sensitive files are tracked by git!"
    echo "   Manual intervention required to remove from git history"
    exit 1
else
    echo "✅ No sensitive files tracked in git repository"
fi

# Check for uncommitted sensitive files
if git status --porcelain | grep -E "\\.(bmad-key|bmad-token)$"; then
    echo "⚠️  Uncommitted sensitive files detected"
    echo "   These files should be moved to secure external storage"
else
    echo "✅ No uncommitted sensitive files detected"
fi

echo ""

echo "4️⃣ IMPLEMENTING SECURITY CONTROLS"
echo "─────────────────────────────────────"

# Make security validation script executable
if [[ -f "security-validation.js" ]]; then
    chmod +x "security-validation.js"
    echo "✅ Security validation script is executable"
fi

# Set up environment template if needed
if [[ ! -f ".env.template" ]] && [[ -f ".claude/validators-node/.env.example" ]]; then
    cat > .env.template << 'EOF'
# BMAD Environment Configuration Template
# Copy this file to .env and configure for your environment
# NEVER commit .env files with actual values to version control

# === BMAD AUTHENTICATION ===
# BMAD_API_KEY=your-bmad-api-key-here
# BMAD_SECRET_KEY=your-bmad-secret-key-here

# === LLM PROVIDER CONFIGURATION ===
# OPENAI_API_KEY=your-openai-api-key-here
# ANTHROPIC_API_KEY=your-anthropic-api-key-here
# GROQ_API_KEY=your-groq-api-key-here

# === SECURITY CONFIGURATION ===
# BMAD_VERIFY_MODE=strict
# BMAD_TOKEN_REQUIRED=true
EOF
    echo "✅ Created .env.template for secure configuration"
fi

echo ""

echo "5️⃣ SETTING UP SECURITY AUTOMATION"
echo "──────────────────────────────────────"

# Create pre-commit hook for security validation
HOOKS_DIR=".git/hooks"
if [[ -d "$HOOKS_DIR" ]]; then
    cat > "$HOOKS_DIR/pre-commit" << 'EOF'
#!/bin/bash
# BMAD Security Pre-commit Hook
# Validates repository security before commits

echo "🔐 Running security validation..."

# Run security validation if script exists
if [[ -f "security-validation.js" ]]; then
    if ! node security-validation.js --quiet; then
        echo "❌ Security validation failed!"
        echo "   Review docs/testing/security/security-validation-results.json for details"
        echo "   Fix security issues before committing"
        exit 1
    fi
fi

# Check for sensitive files
SENSITIVE_FILES=(".bmad-key" ".bmad-token")
for file in "${SENSITIVE_FILES[@]}"; do
    if git diff --cached --name-only | grep -q "^$file$"; then
        echo "❌ Attempting to commit sensitive file: $file"
        echo "   Remove from staging area and use environment variables"
        exit 1
    fi
done

echo "✅ Security validation passed"
EOF

    chmod +x "$HOOKS_DIR/pre-commit"
    echo "✅ Security pre-commit hook installed"
else
    echo "⚠️  Git hooks directory not found - manual pre-commit setup required"
fi

echo ""

echo "6️⃣ GENERATING SECURITY DOCUMENTATION"
echo "────────────────────────────────────────"

# Create security checklist
cat > "SECURITY-CHECKLIST.md" << 'EOF'
# BMAD Security Checklist

## Pre-Deployment Security Verification

### Critical Requirements:
- [ ] No `.bmad-key` file in production deployment
- [ ] No `.bmad-token` file in production deployment
- [ ] All credentials stored in environment variables
- [ ] Security validation passes with 0 critical issues
- [ ] All sensitive files have appropriate permissions (600)

### Code Security:
- [ ] No hardcoded credentials in source code
- [ ] Input validation implemented for all user inputs
- [ ] Command injection vulnerabilities addressed
- [ ] Secure error handling (no information leakage)

### Infrastructure Security:
- [ ] HTTPS/TLS enabled for all external communications
- [ ] Access controls implemented and tested
- [ ] Logging and monitoring configured
- [ ] Incident response procedures documented

### Development Security:
- [ ] Security pre-commit hooks active
- [ ] Dependency vulnerability scanning enabled
- [ ] Regular security training completed
- [ ] Secure coding standards followed

## Security Validation Commands:

```bash
# Run security validation
node security-validation.js

# Check file permissions
ls -la .bmad-key .bmad-token 2>/dev/null || echo "Files not present (good)"

# Verify git status
git status --porcelain | grep -E "\\.(bmad-key|bmad-token)$" || echo "No sensitive files staged (good)"
```

## Emergency Contacts:
- Security Team: security@bmad.ai
- Incident Response: incident@bmad.ai
- On-call Security: [Configure based on team structure]
EOF

echo "✅ Security checklist created: SECURITY-CHECKLIST.md"

echo ""

echo "🎯 REMEDIATION SUMMARY"
echo "═════════════════════"
echo "✅ Sensitive file permissions secured"
echo "✅ Git repository validation completed"
echo "✅ Security automation configured"
echo "✅ Documentation generated"
echo ""
echo "📋 NEXT STEPS:"
echo "   1. Review SECURITY-SANITIZATION-REPORT.md"
echo "   2. Move .bmad-key and .bmad-token to secure external storage"
echo "   3. Configure environment variables for production"
echo "   4. Run: node security-validation.js"
echo "   5. Address any remaining high/critical issues"
echo ""
echo "📊 Current Status: $(node security-validation.js --score 2>/dev/null || echo "Run validation to get score")"
echo ""
echo "🔐 Security remediation completed at: $(date)"
echo "💾 Backup location: $BACKUP_DIR"
echo "📝 Full log: $LOG_FILE"